# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'dracula/tmux'

# Terminal
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Prefix and basic options
unbind C-b
set -g prefix C-a
set -g base-index 1
set -g repeat-time 0
set -g focus-events on
# set -g escape-time 0 
# set -g history-limit 64096
set -g mouse on
set -g renumber-windows on
# set -g set-clipboard on
# set -g set-titles-string "#T"
# set -g set-clipboard on
# set -g status-position top
set -wg automatic-rename on

# Key bindings
# set -w -g mode-keys vi
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
# bind o run-shell "open '#{pane_current_path}'"
# bind -r e kill-pane -a
bind-key -n S-Left swap-window -t -1\; select-window -t -1
bind-key -n S-Right swap-window -t +1\; select-window -t +1
bind-key C-a send-prefix

# TPM
run '~/.config/tmux/plugins/tpm/tpm'
