# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin 'catppuccin/tmux'

# Theme
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"

set -g @catppuccin_window_text " #{window_name}"
set -g @catppuccin_window_current_text " #{window_name}"

set -g status-left ""
set -g status-right ""

run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

# Terminal
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Prefix and basic options
unbind C-b
set -g prefix ^A
# set -g base-index 1
set -g repeat-time 0
set -g focus-events on
set -g escape-time 0 
set -g history-limit 64096
set -g mouse on
set -g renumber-windows on
set -g set-clipboard on
set -g set-titles-string "#T"
set -g set-clipboard on
set -g status-position top
set -wg automatic-rename on

# Key bindings
set -w -g mode-keys vi
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind o run-shell "open '#{pane_current_path}'"
bind -r e kill-pane -a
bind-key -n C-S-Left  swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

# TPM
run '~/.config/tmux/plugins/tpm/tpm'
