alias v="nvim"
alias vim="nvim"
alias cd="z"
alias ls="eza"
alias la="eza -la"
alias ll="eza -l"
alias sourcerc="source ~/.zshrc && source ~/.zprofile"
alias update="brew update && brew upgrade"

alias lms="cd ~/Works/lms/ && pyenv activate lms-env-3.10.12 && nvm use v22.16.0 && ulimit -n 4095"
alias runfront="no_cache=yes WEBPACK_PUBLIC_HOST=localhost yarn dev"
alias runserver="ENV=local no_cache=yes invoke server"
alias lms2="cd ~/Works/lms-web/ && nvm use v22.16.0"
